### ISSUE TITLE
Don't compile

### ISSUE THREAD

**Issue by Droppix** [hipay/hipay-fullservice-sdk-ios#51]
Hi,

I try your project (I use pod install), but I have errors :

-------
ld: warning: ignoring file /Users/robertjuzyna/Downloads/hipay-fullservice-sdk-ios-master/HiPayFullservice/POS/Datecs/DatecsLibrary.framework/DatecsLibrary, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (x86_64): /Users/robertjuzyna/Downloads/hipay-fullservice-sdk-ios-master/HiPayFullservice/POS/Datecs/DatecsLibrary.framework/DatecsLibrary
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PPadCustom", referenced from:
      objc-class-ref in libHiPayFullservice.common-Datecs-POS.a(HPFPOSManager.o)
ld: symbol(s) not found for architecture x86_64
found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
-------

Suggestions?

Thanks

**Comment by legithubdeaymeric** [comment]
Hello,

Sorry for not answering you before.
Do you still have the problem?

Can you tell us the version of your Operating Sytem and your Build Tool?

Did you try to add the lib on an empty project?

If you use Xcode, maybe try a clean from the "~/ Library/Developer/Xcode/DerivedData/" directory

**Comment by Droppix** [comment]
The problem already resolved, with another solution...

**Comment by davidattias** [comment]
@Droppix How did you fix this issue ?
