### ISSUE TITLE
pod 1.7.0 ?

### ISSUE THREAD

**Issue by Droppix** [hipay/hipay-fullservice-sdk-ios#52]
I would like test/integrate "Apple Pay", but the "pod 'HiPayFullservice/Core" is the version 1.3.0.
The version 1.3.0 don't support Apple Play.

what is the solution ?

Thkx

**Comment by aymericfc** [comment]
Hello,

Thank you for your message. The Apple Pay Payment was added to the 1.5.0 version. To have all the last features added you should update (with a pod upadte) to the last version of the SDK (1.7.0) and change your podfile to point to this version. 

Regards,
Aymeric

**Comment by Droppix** [comment]
Thanks.
