### ISSUE TITLE
SEPA

### ISSUE THREAD

**Issue by Droppix** [hipay/hipay-fullservice-sdk-ios#53]
Hi,

I use your SDK iOS in mode Core wrapper (i have owner screens for CB, Apple Pay).
So, I would like integrate SEPA in mode Core Wrapper, and I didn't see any indication in the documentation, is it possible ? If yes, how ?

Thanks
Regards

**Comment by Droppix** [comment]
Can be an answer?

**Comment by legithubdeaymeric** [comment]
Hello,

It is currently not possible to integrate SEPA in Core Wrapper mode.
Missing fields for SEPA such as "bank_name" and "issuer_bank_id" are missing in the HPFOrderRelatedRequest object. It is also missing the payment product "sdd". This is a small feature, we will develop it quickly.

**Comment by Droppix** [comment]
Hi,

We have integrated  Hi-Pay (Core Wrapper mode) in our application, but we need 2 functionality that seems to be not built into the SDK: 

- 3D Secure
- SEPA

What is the release date of this update, which seems to us primoridiale (We have been waiting for it for several months ...)?

Thanks

**Comment by morganHipay** [comment]
Add SEPA Direct Debit with PR #66

**Comment by morganHipay** [comment]
Feature available in [1.9.0](https://github.com/hipay/hipay-fullservice-sdk-ios/releases/tag/1.9.0)
