### ISSUE TITLE
NSPhotoLibraryUsageDescription required for no reason

### ISSUE THREAD

**Issue by davidattias** [hipay/hipay-fullservice-sdk-ios#60]
When submitting my app with HiPayFullServiceSDK included as Pod, App Store Connect requested declaration of NSPhotoLibraryUsageDescription but I can't figure out how it is use and why would it be used ?

Can you explain how the photo library is used and/or where it is used in the code ?

Thanks

**Comment by legithubdeaymeric** [comment]
Hello,

This permission is used for credit card scanning.

Its use is made here:

> - (void) scanCardTableViewCellDidTouchButton: (HPFScanCardTableViewCell *) cell {
> 
>     NSString * mediaType = AVMediaTypeVideo;
>     AVAuthorizationStatus authStatus = [AVCaptureDevice authorizationStatusForMediaType: mediaType];
> 
>     // this method checks if the user has the appropriate permission
>     if (! self.canReadCardWithCamera) {

What kind of integration do you use? ( Core or Native ? )

**Comment by davidattias** [comment]
I'm using Core integration with custom UI and I'm not currently using the credit card scanning feature.

I understand that NSCameraUsageDescription must be used because of the code you quoted above is included in the framework but I don't understand why does it require NSPhotoLibraryDescription ?

**Comment by legithubdeaymeric** [comment]
Oops, sorry I do not know why but I thought NSCameraUsageDescription.

Actually it's not normal for NSPhotoLibraryDescription permission and we're looking at why.

**Comment by davidattias** [comment]
> Oops, sorry I do not know why but I thought NSCameraUsageDescription.
> 
> Actually it's not normal for NSPhotoLibraryDescription permission and we're looking at why.

Any update about this issue ?

**Comment by morganHipay** [comment]
Hello,

If you use the core integration, it’s not possible to have this problem with our SDK.
In fact, we don’t interact with PHAsset, PHPhotoLibrary, and PHImageManager classes.  

Inspect your others pods, you can also read this thread from Apple’s forums : https://forums.developer.apple.com/thread/62229

**Comment by davidattias** [comment]
I’m using only the core but I’m integrating the full sdk. 

The Hipay sdk is the only addition we did and this is the cause of the photo library privacy string requested by iTunes. 

Envoyé de mon iPhone

**Comment by morganHipay** [comment]
@davidattias Did you succeed in correcting the required permission ?
