### ISSUE TITLE
Crash on every Apple Pay payment on 1.9.1

### ISSUE THREAD

**Issue by davidattias** [hipay/hipay-fullservice-sdk-ios#77]
My app "in production" crashes every time a user makes an Apple Pay payment using 1.9.1.

The debugger shows the crashes happens in the init of HPFOrderRelatedRequest object because it can't load the bundle HPFUtilitiesResources.

Reproducible on every try.

**Comment by morganHipay** [comment]
Sorry for the delay.

We fixed the problem with the latest version **1.9.2** on CocoaPods. **Please update your pods and contact us if you have new issues.**

_Explanation : OrderRelatedRequest initialization used HPFUtilitiesResources bundle to retrieve the SDK version but if you install only "Core" Pod, OrderRelatedRequest will not have the possibility to retrieve the SDK version so the integration_version variable will be nil in source dictionary._

**Comment by davidattias** [comment]
Thanks!
