### ISSUE TITLE
DSP2 : deviceChannel

### ISSUE THREAD

**Issue by charles-awayup** [hipay/hipay-fullservice-sdk-ios#82]
Hi,
The device_channel field is mandatory, but it does not seem to be accessible (private).
Also, this one has a default value set to 2 = Browser (BRW)

[https://github.com/hipay/hipay-fullservice-sdk-ios/blob/ea42503f398bd75c23538969f4ee7d334f89b4aa/HiPayFullservice/Core/Gateway/Request/Order/HPFOrderRelatedRequest.m#L53](https://github.com/hipay/hipay-fullservice-sdk-ios/blob/ea42503f398bd75c23538969f4ee7d334f89b4aa/HiPayFullservice/Core/Gateway/Request/Order/HPFOrderRelatedRequest.m#L53)

**Comment by morganHipay** [comment]
Hi,
Yes you are right, the **device_channel** field is private and set to 2 ("Browser") by default.
It is not a mistake, for the moment we are handling in this way. Once the SDK will contain the native screens, we will set it to 1.
